from enum import StrEnum


class AuditAction(StrEnum):
    LOGIN = "LOGIN"
    DEVICE_REGISTER = "DEVICE_REGISTER"
    DEVICE_COMMAND = "DEVICE_COMMAND"
    OTA_UPLOAD = "OTA_UPLOAD"
    RULE_MUTATION = "RULE_MUTATION"
    TENANT_UPDATE = "TENANT_UPDATE"
    DEVICE_PROFILE_CREATE = "DEVICE_PROFILE_CREATE"
    DEVICE_PROFILE_PUBLISH = "DEVICE_PROFILE_PUBLISH"
    DEVICE_PROFILE_ARCHIVE = "DEVICE_PROFILE_ARCHIVE"
